### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by thattommyhall** [solvaholic/octodns-sync#12] opened 2020-09-18 00:33 UTC
I'm new to Actions, but the Dockerfile is not very cachable and it seems odd to me to install octodns via git. 

Is it worth me proposing to change it or is your workflow dependent on the script doing everything in this way

**Comment by solvaholic** [comment] 2020-10-07 13:04
Hi @thattommyhall, thank you for asking!

I don't recall exactly how I arrived at this method, but 1) I do recall it had to do with performance and 2) I'm certain it does not need to stay this way.

(I believe installing dependencies took much longer than downloading a container image that includes them.)

If you'd like to propose changes, please do.

For what it's worth the next updates I'd like to make to this project are to bring versions current and to take advantage of any new (or new-to-me) package and container registry features that will simplify the action or make it faster.

**Comment by solvaholic** [comment] 2020-10-08 13:13
I'd like to share some context, related to this question:

> Is it worth me proposing to change it or is your workflow dependent on the script doing everything in this way

Running `octodns-sync` in a container was faster than installing dependencies at runtime. Another benefit, I think, of the container is a user can run it locally.

To keep the user's `octodns` configuration in their .yaml as much as possible, I set the container up to provide all the dependencies `octodns` may expect.

As a result of those ☝️ the workflow syntax is simple and running the `octodns-sync` container locally shares similar syntax as if `octodns` is installed directly. That is, this workflow step:

```
      - name: Publish
        uses: solvaholic/octodns-sync@v2
        with:
          config_path: public.yaml
          doit: --doit
```

Should work the same as this Docker command:

```
docker run --rm -v "$(realpath .)":/config --env-file .env \
  solvaholic/octodns-sync:2 /config/public.yaml --doit
```

Should work the same as this `octodns-sync` command:

```
octodns-sync --config-file=public.yaml --doit
```

**Comment by solvaholic** [comment] 2020-10-10 03:34
Oh wow!

> I'm new to Actions, but the Dockerfile is not very cachable and it seems odd to me to install octodns via git.

Yeah, I see what you mean now. I thought the Action `@v2` was pulling a Docker image rather than building one.

When I test [with @v2](https://github.com/solvaholic/ideal-octo-pancake/runs/1234359903?check_suite_focus=true) it builds the image, when I test [with @v2.0.0](https://github.com/solvaholic/ideal-octo-pancake/runs/1234363067?check_suite_focus=true) or [with @0c16d1d](https://github.com/solvaholic/ideal-octo-pancake/runs/1234344353?check_suite_focus=true) it pulls an image from Docker hub.

That value appears not to be used how I thought: The tags v2 and v2.0.0 both point to the same commit, so I thought the Action worked the same either way. I have more things to learn.

**Comment by solvaholic** [comment] 2020-10-10 16:11
Ugh. Ok. I'd left a branch named "v2" in solvaholic/octodns-sync. I deleted that and [now the Action pulls the image](https://github.com/solvaholic/ideal-octo-pancake/runs/1235819391?check_suite_focus=true) as intended.

Now what I said in https://github.com/solvaholic/octodns-sync/issues/12#issuecomment-705559209 should be true when using the `@v2` Action.

@thattommyhall I added your `bug` label back - Thank you for letting me know about this!

I'll close this issue, but please re-open it if you'd like to discuss.

**Closed by solvaholic** 2020-10-10 16:11 UTC
Labels: bug, enhancement, question
